name: bookreview
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  go_router: ^14.6.3
  equatable: ^2.0.7
  dio: ^5.7.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3


flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/svg/icons/
    - assets/images/
