name: bookreview
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  go_router: ^14.6.3
  equatable: ^2.0.7
  dio: ^5.7.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  flutter_svg: ^2.0.17
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.6
  image_picker: ^1.1.2
  build_runner: ^2.4.14
  build: ^2.4.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3


flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/svg/icons/
    - assets/images/
